default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "postgres") %>
  database: <%= ENV.fetch("DB_NAME", "salary_management_development") %>

development:
  <<: *default
  database: salary_management_development

test:
  <<: *default
  database: salary_management_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "salary_management_production") %>
