source "https://rubygems.org"

ruby "3.2.2"

gem "bootsnap", ">= 1.4.4", require: false
gem "kaminari", "~> 1.2"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "rack-cors", "~> 2.0"
gem "rails", "~> 7.1.0"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.2"
  gem "rspec-rails", "~> 6.1"
  gem "rubocop", "~> 1.65", require: false
  gem "rubocop-performance", "~> 1.22", require: false
  gem "rubocop-rails", "~> 2.25", require: false
  gem "rubocop-rspec", "~> 2.29", require: false
end

group :test do
  gem "shoulda-matchers", "~> 6.0"
  gem "simplecov", "~> 0.22", require: false
  gem "simplecov-lcov", "~> 0.8", require: false
end
